# Generated by Django 5.1.4 on 2024-12-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_booktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productType',
            field=models.CharField(default='Văn phòng', max_length=255),
        ),
    ]
