# Generated by Django 5.1.4 on 2025-01-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
    ]
