# Generated by Django 5.1.4 on 2025-01-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_product_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(default='gaming', max_length=255),
        ),
    ]
